name: Build - $(Build.BuildId)

trigger:
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/utils/prepare-cache.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/utils/prepare-cache.yml
    
  - job: Linux_opam
    pool:
      vmImage: ubuntu-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
      OPAM_VERSION: 2.0.5
      OPAM_PKG: $(OPAM_VERSION)-x86_64-linux
      OCAML_VERSION: 4.09.0
    steps:
    - template: .ci/build-opam.yml

  # - job: Windows
  #   pool:
  #     vmImage: windows-latest
  #   variables:
  #     ESY__PREFIX: $(Pipeline.Workspace)\.esy
  #   steps:
  #   - template: .ci/build-platform.yml
  #     parameters:
  #       esyLockPath: $(Build.SourcesDirectory)\esy.lock\index.json
  #       installFolderPath: \3_

- stage: Test_versions
  dependsOn: []
  displayName: Test building with multiple OCaml versions
  jobs:
  - job:
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    strategy:
      matrix: 
        4_06_1:
          OCAML_VERSION: 4.06.1
        4_07_1:
          OCAML_VERSION: 4.07.1
        4_08_1:
          OCAML_VERSION: 4.08.1
        4_09_0:
          OCAML_VERSION: 4.09.0
    steps:
      - template: .ci/utils/use-node.yml
      - template: .ci/utils/use-esy.yml
      - template: .ci/utils/cache.yml
        parameters:
          cache_key: esy.lock/index.json | "$(OCAML_VERSION)"
      - bash: ./test-version.sh $(OCAML_VERSION)
        displayName: Test building with OCaml version $(OCAML_VERSION)
      - template: .ci/utils/prepare-cache.yml

- stage: Build_NPM
  displayName: Build NPM packages
  dependsOn: [build, Test_versions]
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: .ci/create-npm-package.yml
      parameters:
        package_name: $(package_name)
